#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowWebService.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ICAudit")]
	public partial class FlowDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void Insertflow_apply(flow_apply instance);
    partial void Updateflow_apply(flow_apply instance);
    partial void Deleteflow_apply(flow_apply instance);
    partial void Insertflow_applyEntry(flow_applyEntry instance);
    partial void Updateflow_applyEntry(flow_applyEntry instance);
    partial void Deleteflow_applyEntry(flow_applyEntry instance);
    partial void Insertflow_template(flow_template instance);
    partial void Updateflow_template(flow_template instance);
    partial void Deleteflow_template(flow_template instance);
    partial void Insertflow_templateEntry(flow_templateEntry instance);
    partial void Updateflow_templateEntry(flow_templateEntry instance);
    partial void Deleteflow_templateEntry(flow_templateEntry instance);
    partial void Insertflow_applyEntryQueue(flow_applyEntryQueue instance);
    partial void Updateflow_applyEntryQueue(flow_applyEntryQueue instance);
    partial void Deleteflow_applyEntryQueue(flow_applyEntryQueue instance);
    partial void Insertei_department(ei_department instance);
    partial void Updateei_department(ei_department instance);
    partial void Deleteei_department(ei_department instance);
    partial void Insertei_departmentAuditNode(ei_departmentAuditNode instance);
    partial void Updateei_departmentAuditNode(ei_departmentAuditNode instance);
    partial void Deleteei_departmentAuditNode(ei_departmentAuditNode instance);
    partial void Insertei_departmentAuditUser(ei_departmentAuditUser instance);
    partial void Updateei_departmentAuditUser(ei_departmentAuditUser instance);
    partial void Deleteei_departmentAuditUser(ei_departmentAuditUser instance);
    partial void Insertei_workAgent(ei_workAgent instance);
    partial void Updateei_workAgent(ei_workAgent instance);
    partial void Deleteei_workAgent(ei_workAgent instance);
    #endregion
		
		public FlowDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ICAuditConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public FlowDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FlowDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FlowDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FlowDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<flow_apply> flow_apply
		{
			get
			{
				return this.GetTable<flow_apply>();
			}
		}
		
		public System.Data.Linq.Table<flow_applyEntry> flow_applyEntry
		{
			get
			{
				return this.GetTable<flow_applyEntry>();
			}
		}
		
		public System.Data.Linq.Table<flow_template> flow_template
		{
			get
			{
				return this.GetTable<flow_template>();
			}
		}
		
		public System.Data.Linq.Table<flow_templateEntry> flow_templateEntry
		{
			get
			{
				return this.GetTable<flow_templateEntry>();
			}
		}
		
		public System.Data.Linq.Table<vw_dp_repairman> vw_dp_repairman
		{
			get
			{
				return this.GetTable<vw_dp_repairman>();
			}
		}
		
		public System.Data.Linq.Table<flow_applyEntryQueue> flow_applyEntryQueue
		{
			get
			{
				return this.GetTable<flow_applyEntryQueue>();
			}
		}
		
		public System.Data.Linq.Table<ei_department> ei_department
		{
			get
			{
				return this.GetTable<ei_department>();
			}
		}
		
		public System.Data.Linq.Table<ei_departmentAuditNode> ei_departmentAuditNode
		{
			get
			{
				return this.GetTable<ei_departmentAuditNode>();
			}
		}
		
		public System.Data.Linq.Table<ei_departmentAuditUser> ei_departmentAuditUser
		{
			get
			{
				return this.GetTable<ei_departmentAuditUser>();
			}
		}
		
		public System.Data.Linq.Table<vw_leaving_days> vw_leaving_days
		{
			get
			{
				return this.GetTable<vw_leaving_days>();
			}
		}
		
		public System.Data.Linq.Table<ei_workAgent> ei_workAgent
		{
			get
			{
				return this.GetTable<ei_workAgent>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DP_InsertRepairCost")]
		public int DP_InsertRepairCost([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string dorm_number, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string emp_card, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(8,2)")] System.Nullable<decimal> repair_cost, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string sys_no, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(500)")] string repair_subject, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string year_month)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dorm_number, emp_card, repair_cost, sys_no, repair_subject, year_month);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.flow_apply")]
	public partial class flow_apply : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _flow_template_id;
		
		private string _create_user;
		
		private System.Nullable<bool> _success;
		
		private System.Nullable<System.DateTime> _start_date;
		
		private System.Nullable<System.DateTime> _finish_date;
		
		private string _sys_no;
		
		private string _form_title;
		
		private string _form_sub_title;
		
		private System.Nullable<bool> _user_abort;
		
		private EntitySet<flow_applyEntry> _flow_applyEntry;
		
		private EntityRef<flow_template> _flow_template;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onflow_template_idChanging(System.Nullable<int> value);
    partial void Onflow_template_idChanged();
    partial void Oncreate_userChanging(string value);
    partial void Oncreate_userChanged();
    partial void OnsuccessChanging(System.Nullable<bool> value);
    partial void OnsuccessChanged();
    partial void Onstart_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onstart_dateChanged();
    partial void Onfinish_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onfinish_dateChanged();
    partial void Onsys_noChanging(string value);
    partial void Onsys_noChanged();
    partial void Onform_titleChanging(string value);
    partial void Onform_titleChanged();
    partial void Onform_sub_titleChanging(string value);
    partial void Onform_sub_titleChanged();
    partial void Onuser_abortChanging(System.Nullable<bool> value);
    partial void Onuser_abortChanged();
    #endregion
		
		public flow_apply()
		{
			this._flow_applyEntry = new EntitySet<flow_applyEntry>(new Action<flow_applyEntry>(this.attach_flow_applyEntry), new Action<flow_applyEntry>(this.detach_flow_applyEntry));
			this._flow_template = default(EntityRef<flow_template>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flow_template_id", DbType="Int")]
		public System.Nullable<int> flow_template_id
		{
			get
			{
				return this._flow_template_id;
			}
			set
			{
				if ((this._flow_template_id != value))
				{
					if (this._flow_template.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onflow_template_idChanging(value);
					this.SendPropertyChanging();
					this._flow_template_id = value;
					this.SendPropertyChanged("flow_template_id");
					this.Onflow_template_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_user", DbType="VarChar(50)")]
		public string create_user
		{
			get
			{
				return this._create_user;
			}
			set
			{
				if ((this._create_user != value))
				{
					this.Oncreate_userChanging(value);
					this.SendPropertyChanging();
					this._create_user = value;
					this.SendPropertyChanged("create_user");
					this.Oncreate_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_success", DbType="Bit")]
		public System.Nullable<bool> success
		{
			get
			{
				return this._success;
			}
			set
			{
				if ((this._success != value))
				{
					this.OnsuccessChanging(value);
					this.SendPropertyChanging();
					this._success = value;
					this.SendPropertyChanged("success");
					this.OnsuccessChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_start_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> start_date
		{
			get
			{
				return this._start_date;
			}
			set
			{
				if ((this._start_date != value))
				{
					this.Onstart_dateChanging(value);
					this.SendPropertyChanging();
					this._start_date = value;
					this.SendPropertyChanged("start_date");
					this.Onstart_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_finish_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> finish_date
		{
			get
			{
				return this._finish_date;
			}
			set
			{
				if ((this._finish_date != value))
				{
					this.Onfinish_dateChanging(value);
					this.SendPropertyChanging();
					this._finish_date = value;
					this.SendPropertyChanged("finish_date");
					this.Onfinish_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sys_no", DbType="VarChar(50)")]
		public string sys_no
		{
			get
			{
				return this._sys_no;
			}
			set
			{
				if ((this._sys_no != value))
				{
					this.Onsys_noChanging(value);
					this.SendPropertyChanging();
					this._sys_no = value;
					this.SendPropertyChanged("sys_no");
					this.Onsys_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_form_title", DbType="VarChar(500)")]
		public string form_title
		{
			get
			{
				return this._form_title;
			}
			set
			{
				if ((this._form_title != value))
				{
					this.Onform_titleChanging(value);
					this.SendPropertyChanging();
					this._form_title = value;
					this.SendPropertyChanged("form_title");
					this.Onform_titleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_form_sub_title", DbType="VarChar(500)")]
		public string form_sub_title
		{
			get
			{
				return this._form_sub_title;
			}
			set
			{
				if ((this._form_sub_title != value))
				{
					this.Onform_sub_titleChanging(value);
					this.SendPropertyChanging();
					this._form_sub_title = value;
					this.SendPropertyChanged("form_sub_title");
					this.Onform_sub_titleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_abort", DbType="bit")]
		public System.Nullable<bool> user_abort
		{
			get
			{
				return this._user_abort;
			}
			set
			{
				if ((this._user_abort != value))
				{
					this.Onuser_abortChanging(value);
					this.SendPropertyChanging();
					this._user_abort = value;
					this.SendPropertyChanged("user_abort");
					this.Onuser_abortChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="flow_apply_flow_applyEntry", Storage="_flow_applyEntry", ThisKey="id", OtherKey="apply_id")]
		public EntitySet<flow_applyEntry> flow_applyEntry
		{
			get
			{
				return this._flow_applyEntry;
			}
			set
			{
				this._flow_applyEntry.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="flow_template_flow_apply", Storage="_flow_template", ThisKey="flow_template_id", OtherKey="id", IsForeignKey=true)]
		public flow_template flow_template
		{
			get
			{
				return this._flow_template.Entity;
			}
			set
			{
				flow_template previousValue = this._flow_template.Entity;
				if (((previousValue != value) 
							|| (this._flow_template.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._flow_template.Entity = null;
						previousValue.flow_apply.Remove(this);
					}
					this._flow_template.Entity = value;
					if ((value != null))
					{
						value.flow_apply.Add(this);
						this._flow_template_id = value.id;
					}
					else
					{
						this._flow_template_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("flow_template");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_flow_applyEntry(flow_applyEntry entity)
		{
			this.SendPropertyChanging();
			entity.flow_apply = this;
		}
		
		private void detach_flow_applyEntry(flow_applyEntry entity)
		{
			this.SendPropertyChanging();
			entity.flow_apply = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.flow_applyEntry")]
	public partial class flow_applyEntry : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _apply_id;
		
		private string _auditors;
		
		private System.Nullable<bool> _pass;
		
		private System.Nullable<System.DateTime> _audit_time;
		
		private string _opinion;
		
		private System.Nullable<int> _step;
		
		private string _step_name;
		
		private System.Nullable<int> _flow_template_entry_id;
		
		private string _final_auditor;
		
		private EntityRef<flow_apply> _flow_apply;
		
		private EntityRef<flow_templateEntry> _flow_templateEntry;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onapply_idChanging(System.Nullable<int> value);
    partial void Onapply_idChanged();
    partial void OnauditorsChanging(string value);
    partial void OnauditorsChanged();
    partial void OnpassChanging(System.Nullable<bool> value);
    partial void OnpassChanged();
    partial void Onaudit_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onaudit_timeChanged();
    partial void OnopinionChanging(string value);
    partial void OnopinionChanged();
    partial void OnstepChanging(System.Nullable<int> value);
    partial void OnstepChanged();
    partial void Onstep_nameChanging(string value);
    partial void Onstep_nameChanged();
    partial void Onflow_template_entry_idChanging(System.Nullable<int> value);
    partial void Onflow_template_entry_idChanged();
    partial void Onfinal_auditorChanging(string value);
    partial void Onfinal_auditorChanged();
    #endregion
		
		public flow_applyEntry()
		{
			this._flow_apply = default(EntityRef<flow_apply>);
			this._flow_templateEntry = default(EntityRef<flow_templateEntry>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apply_id", DbType="Int")]
		public System.Nullable<int> apply_id
		{
			get
			{
				return this._apply_id;
			}
			set
			{
				if ((this._apply_id != value))
				{
					if (this._flow_apply.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onapply_idChanging(value);
					this.SendPropertyChanging();
					this._apply_id = value;
					this.SendPropertyChanged("apply_id");
					this.Onapply_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_auditors", DbType="VarChar(500)")]
		public string auditors
		{
			get
			{
				return this._auditors;
			}
			set
			{
				if ((this._auditors != value))
				{
					this.OnauditorsChanging(value);
					this.SendPropertyChanging();
					this._auditors = value;
					this.SendPropertyChanged("auditors");
					this.OnauditorsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pass", DbType="Bit")]
		public System.Nullable<bool> pass
		{
			get
			{
				return this._pass;
			}
			set
			{
				if ((this._pass != value))
				{
					this.OnpassChanging(value);
					this.SendPropertyChanging();
					this._pass = value;
					this.SendPropertyChanged("pass");
					this.OnpassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_audit_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> audit_time
		{
			get
			{
				return this._audit_time;
			}
			set
			{
				if ((this._audit_time != value))
				{
					this.Onaudit_timeChanging(value);
					this.SendPropertyChanging();
					this._audit_time = value;
					this.SendPropertyChanged("audit_time");
					this.Onaudit_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_opinion", DbType="VarChar(500)")]
		public string opinion
		{
			get
			{
				return this._opinion;
			}
			set
			{
				if ((this._opinion != value))
				{
					this.OnopinionChanging(value);
					this.SendPropertyChanging();
					this._opinion = value;
					this.SendPropertyChanged("opinion");
					this.OnopinionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_step", DbType="Int")]
		public System.Nullable<int> step
		{
			get
			{
				return this._step;
			}
			set
			{
				if ((this._step != value))
				{
					this.OnstepChanging(value);
					this.SendPropertyChanging();
					this._step = value;
					this.SendPropertyChanged("step");
					this.OnstepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_step_name", DbType="VarChar(50)")]
		public string step_name
		{
			get
			{
				return this._step_name;
			}
			set
			{
				if ((this._step_name != value))
				{
					this.Onstep_nameChanging(value);
					this.SendPropertyChanging();
					this._step_name = value;
					this.SendPropertyChanged("step_name");
					this.Onstep_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flow_template_entry_id", DbType="Int")]
		public System.Nullable<int> flow_template_entry_id
		{
			get
			{
				return this._flow_template_entry_id;
			}
			set
			{
				if ((this._flow_template_entry_id != value))
				{
					if (this._flow_templateEntry.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onflow_template_entry_idChanging(value);
					this.SendPropertyChanging();
					this._flow_template_entry_id = value;
					this.SendPropertyChanged("flow_template_entry_id");
					this.Onflow_template_entry_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_final_auditor", DbType="VarChar(50)")]
		public string final_auditor
		{
			get
			{
				return this._final_auditor;
			}
			set
			{
				if ((this._final_auditor != value))
				{
					this.Onfinal_auditorChanging(value);
					this.SendPropertyChanging();
					this._final_auditor = value;
					this.SendPropertyChanged("final_auditor");
					this.Onfinal_auditorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="flow_apply_flow_applyEntry", Storage="_flow_apply", ThisKey="apply_id", OtherKey="id", IsForeignKey=true)]
		public flow_apply flow_apply
		{
			get
			{
				return this._flow_apply.Entity;
			}
			set
			{
				flow_apply previousValue = this._flow_apply.Entity;
				if (((previousValue != value) 
							|| (this._flow_apply.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._flow_apply.Entity = null;
						previousValue.flow_applyEntry.Remove(this);
					}
					this._flow_apply.Entity = value;
					if ((value != null))
					{
						value.flow_applyEntry.Add(this);
						this._apply_id = value.id;
					}
					else
					{
						this._apply_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("flow_apply");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="flow_templateEntry_flow_applyEntry", Storage="_flow_templateEntry", ThisKey="flow_template_entry_id", OtherKey="id", IsForeignKey=true)]
		public flow_templateEntry flow_templateEntry
		{
			get
			{
				return this._flow_templateEntry.Entity;
			}
			set
			{
				flow_templateEntry previousValue = this._flow_templateEntry.Entity;
				if (((previousValue != value) 
							|| (this._flow_templateEntry.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._flow_templateEntry.Entity = null;
						previousValue.flow_applyEntry.Remove(this);
					}
					this._flow_templateEntry.Entity = value;
					if ((value != null))
					{
						value.flow_applyEntry.Add(this);
						this._flow_template_entry_id = value.id;
					}
					else
					{
						this._flow_template_entry_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("flow_templateEntry");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.flow_template")]
	public partial class flow_template : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private bool _enable;
		
		private System.Nullable<System.DateTime> _effective_date;
		
		private System.Nullable<System.DateTime> _expire_date;
		
		private string _bill_type;
		
		private string _summary;
		
		private System.Nullable<System.DateTime> _create_date;
		
		private string _creater;
		
		private EntitySet<flow_apply> _flow_apply;
		
		private EntitySet<flow_templateEntry> _flow_templateEntry;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnenableChanging(bool value);
    partial void OnenableChanged();
    partial void Oneffective_dateChanging(System.Nullable<System.DateTime> value);
    partial void Oneffective_dateChanged();
    partial void Onexpire_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onexpire_dateChanged();
    partial void Onbill_typeChanging(string value);
    partial void Onbill_typeChanged();
    partial void OnsummaryChanging(string value);
    partial void OnsummaryChanged();
    partial void Oncreate_dateChanging(System.Nullable<System.DateTime> value);
    partial void Oncreate_dateChanged();
    partial void OncreaterChanging(string value);
    partial void OncreaterChanged();
    #endregion
		
		public flow_template()
		{
			this._flow_apply = new EntitySet<flow_apply>(new Action<flow_apply>(this.attach_flow_apply), new Action<flow_apply>(this.detach_flow_apply));
			this._flow_templateEntry = new EntitySet<flow_templateEntry>(new Action<flow_templateEntry>(this.attach_flow_templateEntry), new Action<flow_templateEntry>(this.detach_flow_templateEntry));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enable", DbType="Bit NOT NULL")]
		public bool enable
		{
			get
			{
				return this._enable;
			}
			set
			{
				if ((this._enable != value))
				{
					this.OnenableChanging(value);
					this.SendPropertyChanging();
					this._enable = value;
					this.SendPropertyChanged("enable");
					this.OnenableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_effective_date", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> effective_date
		{
			get
			{
				return this._effective_date;
			}
			set
			{
				if ((this._effective_date != value))
				{
					this.Oneffective_dateChanging(value);
					this.SendPropertyChanging();
					this._effective_date = value;
					this.SendPropertyChanged("effective_date");
					this.Oneffective_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_expire_date", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> expire_date
		{
			get
			{
				return this._expire_date;
			}
			set
			{
				if ((this._expire_date != value))
				{
					this.Onexpire_dateChanging(value);
					this.SendPropertyChanging();
					this._expire_date = value;
					this.SendPropertyChanged("expire_date");
					this.Onexpire_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bill_type", DbType="VarChar(20)")]
		public string bill_type
		{
			get
			{
				return this._bill_type;
			}
			set
			{
				if ((this._bill_type != value))
				{
					this.Onbill_typeChanging(value);
					this.SendPropertyChanging();
					this._bill_type = value;
					this.SendPropertyChanged("bill_type");
					this.Onbill_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_summary", DbType="VarChar(200)")]
		public string summary
		{
			get
			{
				return this._summary;
			}
			set
			{
				if ((this._summary != value))
				{
					this.OnsummaryChanging(value);
					this.SendPropertyChanging();
					this._summary = value;
					this.SendPropertyChanged("summary");
					this.OnsummaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> create_date
		{
			get
			{
				return this._create_date;
			}
			set
			{
				if ((this._create_date != value))
				{
					this.Oncreate_dateChanging(value);
					this.SendPropertyChanging();
					this._create_date = value;
					this.SendPropertyChanged("create_date");
					this.Oncreate_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creater", DbType="VarChar(50)")]
		public string creater
		{
			get
			{
				return this._creater;
			}
			set
			{
				if ((this._creater != value))
				{
					this.OncreaterChanging(value);
					this.SendPropertyChanging();
					this._creater = value;
					this.SendPropertyChanged("creater");
					this.OncreaterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="flow_template_flow_apply", Storage="_flow_apply", ThisKey="id", OtherKey="flow_template_id")]
		public EntitySet<flow_apply> flow_apply
		{
			get
			{
				return this._flow_apply;
			}
			set
			{
				this._flow_apply.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="flow_template_flow_templateEntry", Storage="_flow_templateEntry", ThisKey="id", OtherKey="flow_id")]
		public EntitySet<flow_templateEntry> flow_templateEntry
		{
			get
			{
				return this._flow_templateEntry;
			}
			set
			{
				this._flow_templateEntry.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_flow_apply(flow_apply entity)
		{
			this.SendPropertyChanging();
			entity.flow_template = this;
		}
		
		private void detach_flow_apply(flow_apply entity)
		{
			this.SendPropertyChanging();
			entity.flow_template = null;
		}
		
		private void attach_flow_templateEntry(flow_templateEntry entity)
		{
			this.SendPropertyChanging();
			entity.flow_template = this;
		}
		
		private void detach_flow_templateEntry(flow_templateEntry entity)
		{
			this.SendPropertyChanging();
			entity.flow_template = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.flow_templateEntry")]
	public partial class flow_templateEntry : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _flow_id;
		
		private System.Nullable<int> _step;
		
		private string _step_name;
		
		private string _auditors;
		
		private bool _can_be_null;
		
		private bool _countersign;
		
		private string _pass_callback;
		
		private string _ng_callback;
		
		private EntitySet<flow_applyEntry> _flow_applyEntry;
		
		private EntityRef<flow_template> _flow_template;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onflow_idChanging(System.Nullable<int> value);
    partial void Onflow_idChanged();
    partial void OnstepChanging(System.Nullable<int> value);
    partial void OnstepChanged();
    partial void Onstep_nameChanging(string value);
    partial void Onstep_nameChanged();
    partial void OnauditorsChanging(string value);
    partial void OnauditorsChanged();
    partial void Oncan_be_nullChanging(bool value);
    partial void Oncan_be_nullChanged();
    partial void OncountersignChanging(bool value);
    partial void OncountersignChanged();
    partial void Onpass_callbackChanging(string value);
    partial void Onpass_callbackChanged();
    partial void Onng_callbackChanging(string value);
    partial void Onng_callbackChanged();
    #endregion
		
		public flow_templateEntry()
		{
			this._flow_applyEntry = new EntitySet<flow_applyEntry>(new Action<flow_applyEntry>(this.attach_flow_applyEntry), new Action<flow_applyEntry>(this.detach_flow_applyEntry));
			this._flow_template = default(EntityRef<flow_template>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flow_id", DbType="Int")]
		public System.Nullable<int> flow_id
		{
			get
			{
				return this._flow_id;
			}
			set
			{
				if ((this._flow_id != value))
				{
					if (this._flow_template.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onflow_idChanging(value);
					this.SendPropertyChanging();
					this._flow_id = value;
					this.SendPropertyChanged("flow_id");
					this.Onflow_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_step", DbType="Int")]
		public System.Nullable<int> step
		{
			get
			{
				return this._step;
			}
			set
			{
				if ((this._step != value))
				{
					this.OnstepChanging(value);
					this.SendPropertyChanging();
					this._step = value;
					this.SendPropertyChanged("step");
					this.OnstepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_step_name", DbType="VarChar(50)")]
		public string step_name
		{
			get
			{
				return this._step_name;
			}
			set
			{
				if ((this._step_name != value))
				{
					this.Onstep_nameChanging(value);
					this.SendPropertyChanging();
					this._step_name = value;
					this.SendPropertyChanged("step_name");
					this.Onstep_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_auditors", DbType="VarChar(500)")]
		public string auditors
		{
			get
			{
				return this._auditors;
			}
			set
			{
				if ((this._auditors != value))
				{
					this.OnauditorsChanging(value);
					this.SendPropertyChanging();
					this._auditors = value;
					this.SendPropertyChanged("auditors");
					this.OnauditorsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_can_be_null", DbType="Bit NOT NULL")]
		public bool can_be_null
		{
			get
			{
				return this._can_be_null;
			}
			set
			{
				if ((this._can_be_null != value))
				{
					this.Oncan_be_nullChanging(value);
					this.SendPropertyChanging();
					this._can_be_null = value;
					this.SendPropertyChanged("can_be_null");
					this.Oncan_be_nullChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_countersign", DbType="Bit NOT NULL")]
		public bool countersign
		{
			get
			{
				return this._countersign;
			}
			set
			{
				if ((this._countersign != value))
				{
					this.OncountersignChanging(value);
					this.SendPropertyChanging();
					this._countersign = value;
					this.SendPropertyChanged("countersign");
					this.OncountersignChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pass_callback", DbType="VarChar(50)")]
		public string pass_callback
		{
			get
			{
				return this._pass_callback;
			}
			set
			{
				if ((this._pass_callback != value))
				{
					this.Onpass_callbackChanging(value);
					this.SendPropertyChanging();
					this._pass_callback = value;
					this.SendPropertyChanged("pass_callback");
					this.Onpass_callbackChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ng_callback", DbType="VarChar(50)")]
		public string ng_callback
		{
			get
			{
				return this._ng_callback;
			}
			set
			{
				if ((this._ng_callback != value))
				{
					this.Onng_callbackChanging(value);
					this.SendPropertyChanging();
					this._ng_callback = value;
					this.SendPropertyChanged("ng_callback");
					this.Onng_callbackChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="flow_templateEntry_flow_applyEntry", Storage="_flow_applyEntry", ThisKey="id", OtherKey="flow_template_entry_id")]
		public EntitySet<flow_applyEntry> flow_applyEntry
		{
			get
			{
				return this._flow_applyEntry;
			}
			set
			{
				this._flow_applyEntry.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="flow_template_flow_templateEntry", Storage="_flow_template", ThisKey="flow_id", OtherKey="id", IsForeignKey=true)]
		public flow_template flow_template
		{
			get
			{
				return this._flow_template.Entity;
			}
			set
			{
				flow_template previousValue = this._flow_template.Entity;
				if (((previousValue != value) 
							|| (this._flow_template.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._flow_template.Entity = null;
						previousValue.flow_templateEntry.Remove(this);
					}
					this._flow_template.Entity = value;
					if ((value != null))
					{
						value.flow_templateEntry.Add(this);
						this._flow_id = value.id;
					}
					else
					{
						this._flow_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("flow_template");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_flow_applyEntry(flow_applyEntry entity)
		{
			this.SendPropertyChanging();
			entity.flow_templateEntry = this;
		}
		
		private void detach_flow_applyEntry(flow_applyEntry entity)
		{
			this.SendPropertyChanging();
			entity.flow_templateEntry = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_dp_repairman")]
	public partial class vw_dp_repairman
	{
		
		private string _area_name;
		
		private string _repairman_card_number;
		
		public vw_dp_repairman()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_area_name", DbType="VarChar(50)")]
		public string area_name
		{
			get
			{
				return this._area_name;
			}
			set
			{
				if ((this._area_name != value))
				{
					this._area_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_repairman_card_number", DbType="VarChar(200)")]
		public string repairman_card_number
		{
			get
			{
				return this._repairman_card_number;
			}
			set
			{
				if ((this._repairman_card_number != value))
				{
					this._repairman_card_number = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.flow_applyEntryQueue")]
	public partial class flow_applyEntryQueue : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _sys_no;
		
		private System.Nullable<int> _step;
		
		private string _step_name;
		
		private string _auditors;
		
		private System.Nullable<bool> _countersign;
		
		private System.Nullable<int> _flow_template_entry_id;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onsys_noChanging(string value);
    partial void Onsys_noChanged();
    partial void OnstepChanging(System.Nullable<int> value);
    partial void OnstepChanged();
    partial void Onstep_nameChanging(string value);
    partial void Onstep_nameChanged();
    partial void OnauditorsChanging(string value);
    partial void OnauditorsChanged();
    partial void OncountersignChanging(System.Nullable<bool> value);
    partial void OncountersignChanged();
    partial void Onflow_template_entry_idChanging(System.Nullable<int> value);
    partial void Onflow_template_entry_idChanged();
    #endregion
		
		public flow_applyEntryQueue()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sys_no", DbType="VarChar(50)")]
		public string sys_no
		{
			get
			{
				return this._sys_no;
			}
			set
			{
				if ((this._sys_no != value))
				{
					this.Onsys_noChanging(value);
					this.SendPropertyChanging();
					this._sys_no = value;
					this.SendPropertyChanged("sys_no");
					this.Onsys_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_step", DbType="Int")]
		public System.Nullable<int> step
		{
			get
			{
				return this._step;
			}
			set
			{
				if ((this._step != value))
				{
					this.OnstepChanging(value);
					this.SendPropertyChanging();
					this._step = value;
					this.SendPropertyChanged("step");
					this.OnstepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_step_name", DbType="VarChar(50)")]
		public string step_name
		{
			get
			{
				return this._step_name;
			}
			set
			{
				if ((this._step_name != value))
				{
					this.Onstep_nameChanging(value);
					this.SendPropertyChanging();
					this._step_name = value;
					this.SendPropertyChanged("step_name");
					this.Onstep_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_auditors", DbType="VarChar(500)")]
		public string auditors
		{
			get
			{
				return this._auditors;
			}
			set
			{
				if ((this._auditors != value))
				{
					this.OnauditorsChanging(value);
					this.SendPropertyChanging();
					this._auditors = value;
					this.SendPropertyChanged("auditors");
					this.OnauditorsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_countersign", DbType="Bit")]
		public System.Nullable<bool> countersign
		{
			get
			{
				return this._countersign;
			}
			set
			{
				if ((this._countersign != value))
				{
					this.OncountersignChanging(value);
					this.SendPropertyChanging();
					this._countersign = value;
					this.SendPropertyChanged("countersign");
					this.OncountersignChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flow_template_entry_id", DbType="Int")]
		public System.Nullable<int> flow_template_entry_id
		{
			get
			{
				return this._flow_template_entry_id;
			}
			set
			{
				if ((this._flow_template_entry_id != value))
				{
					this.Onflow_template_entry_idChanging(value);
					this.SendPropertyChanging();
					this._flow_template_entry_id = value;
					this.SendPropertyChanged("flow_template_entry_id");
					this.Onflow_template_entry_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ei_department")]
	public partial class ei_department : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _FNumber;
		
		private string _FName;
		
		private string _FAdmin;
		
		private string _FParent;
		
		private System.Nullable<bool> _FIsDeleted;
		
		private System.Nullable<bool> _FIsForbit;
		
		private string _FCreator;
		
		private System.Nullable<System.DateTime> _FCreateDate;
		
		private System.Nullable<bool> _FIsAuditNode;
		
		private EntitySet<ei_departmentAuditNode> _ei_departmentAuditNode;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnFNumberChanging(string value);
    partial void OnFNumberChanged();
    partial void OnFNameChanging(string value);
    partial void OnFNameChanged();
    partial void OnFAdminChanging(string value);
    partial void OnFAdminChanged();
    partial void OnFParentChanging(string value);
    partial void OnFParentChanged();
    partial void OnFIsDeletedChanging(System.Nullable<bool> value);
    partial void OnFIsDeletedChanged();
    partial void OnFIsForbitChanging(System.Nullable<bool> value);
    partial void OnFIsForbitChanged();
    partial void OnFCreatorChanging(string value);
    partial void OnFCreatorChanged();
    partial void OnFCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnFCreateDateChanged();
    partial void OnFIsAuditNodeChanging(System.Nullable<bool> value);
    partial void OnFIsAuditNodeChanged();
    #endregion
		
		public ei_department()
		{
			this._ei_departmentAuditNode = new EntitySet<ei_departmentAuditNode>(new Action<ei_departmentAuditNode>(this.attach_ei_departmentAuditNode), new Action<ei_departmentAuditNode>(this.detach_ei_departmentAuditNode));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FNumber", DbType="VarChar(500)")]
		public string FNumber
		{
			get
			{
				return this._FNumber;
			}
			set
			{
				if ((this._FNumber != value))
				{
					this.OnFNumberChanging(value);
					this.SendPropertyChanging();
					this._FNumber = value;
					this.SendPropertyChanged("FNumber");
					this.OnFNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FName", DbType="VarChar(100)")]
		public string FName
		{
			get
			{
				return this._FName;
			}
			set
			{
				if ((this._FName != value))
				{
					this.OnFNameChanging(value);
					this.SendPropertyChanging();
					this._FName = value;
					this.SendPropertyChanged("FName");
					this.OnFNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAdmin", DbType="VarChar(500)")]
		public string FAdmin
		{
			get
			{
				return this._FAdmin;
			}
			set
			{
				if ((this._FAdmin != value))
				{
					this.OnFAdminChanging(value);
					this.SendPropertyChanging();
					this._FAdmin = value;
					this.SendPropertyChanged("FAdmin");
					this.OnFAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FParent", DbType="VarChar(500)")]
		public string FParent
		{
			get
			{
				return this._FParent;
			}
			set
			{
				if ((this._FParent != value))
				{
					this.OnFParentChanging(value);
					this.SendPropertyChanging();
					this._FParent = value;
					this.SendPropertyChanged("FParent");
					this.OnFParentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIsDeleted", DbType="Bit")]
		public System.Nullable<bool> FIsDeleted
		{
			get
			{
				return this._FIsDeleted;
			}
			set
			{
				if ((this._FIsDeleted != value))
				{
					this.OnFIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._FIsDeleted = value;
					this.SendPropertyChanged("FIsDeleted");
					this.OnFIsDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIsForbit", DbType="Bit")]
		public System.Nullable<bool> FIsForbit
		{
			get
			{
				return this._FIsForbit;
			}
			set
			{
				if ((this._FIsForbit != value))
				{
					this.OnFIsForbitChanging(value);
					this.SendPropertyChanging();
					this._FIsForbit = value;
					this.SendPropertyChanged("FIsForbit");
					this.OnFIsForbitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FCreator", DbType="VarChar(50)")]
		public string FCreator
		{
			get
			{
				return this._FCreator;
			}
			set
			{
				if ((this._FCreator != value))
				{
					this.OnFCreatorChanging(value);
					this.SendPropertyChanging();
					this._FCreator = value;
					this.SendPropertyChanged("FCreator");
					this.OnFCreatorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FCreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> FCreateDate
		{
			get
			{
				return this._FCreateDate;
			}
			set
			{
				if ((this._FCreateDate != value))
				{
					this.OnFCreateDateChanging(value);
					this.SendPropertyChanging();
					this._FCreateDate = value;
					this.SendPropertyChanged("FCreateDate");
					this.OnFCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIsAuditNode", DbType="Bit")]
		public System.Nullable<bool> FIsAuditNode
		{
			get
			{
				return this._FIsAuditNode;
			}
			set
			{
				if ((this._FIsAuditNode != value))
				{
					this.OnFIsAuditNodeChanging(value);
					this.SendPropertyChanging();
					this._FIsAuditNode = value;
					this.SendPropertyChanged("FIsAuditNode");
					this.OnFIsAuditNodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ei_department_ei_departmentAuditNode", Storage="_ei_departmentAuditNode", ThisKey="id", OtherKey="FDepartmentId")]
		public EntitySet<ei_departmentAuditNode> ei_departmentAuditNode
		{
			get
			{
				return this._ei_departmentAuditNode;
			}
			set
			{
				this._ei_departmentAuditNode.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ei_departmentAuditNode(ei_departmentAuditNode entity)
		{
			this.SendPropertyChanging();
			entity.ei_department = this;
		}
		
		private void detach_ei_departmentAuditNode(ei_departmentAuditNode entity)
		{
			this.SendPropertyChanging();
			entity.ei_department = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ei_departmentAuditNode")]
	public partial class ei_departmentAuditNode : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _FDepartmentId;
		
		private System.Nullable<bool> _FIsCounterSign;
		
		private string _FAuditNodeName;
		
		private string _FProcessName;
		
		private EntitySet<ei_departmentAuditUser> _ei_departmentAuditUser;
		
		private EntityRef<ei_department> _ei_department;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnFDepartmentIdChanging(System.Nullable<int> value);
    partial void OnFDepartmentIdChanged();
    partial void OnFIsCounterSignChanging(System.Nullable<bool> value);
    partial void OnFIsCounterSignChanged();
    partial void OnFAuditNodeNameChanging(string value);
    partial void OnFAuditNodeNameChanged();
    partial void OnFProcessNameChanging(string value);
    partial void OnFProcessNameChanged();
    #endregion
		
		public ei_departmentAuditNode()
		{
			this._ei_departmentAuditUser = new EntitySet<ei_departmentAuditUser>(new Action<ei_departmentAuditUser>(this.attach_ei_departmentAuditUser), new Action<ei_departmentAuditUser>(this.detach_ei_departmentAuditUser));
			this._ei_department = default(EntityRef<ei_department>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FDepartmentId", DbType="Int")]
		public System.Nullable<int> FDepartmentId
		{
			get
			{
				return this._FDepartmentId;
			}
			set
			{
				if ((this._FDepartmentId != value))
				{
					if (this._ei_department.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFDepartmentIdChanging(value);
					this.SendPropertyChanging();
					this._FDepartmentId = value;
					this.SendPropertyChanged("FDepartmentId");
					this.OnFDepartmentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIsCounterSign", DbType="Bit")]
		public System.Nullable<bool> FIsCounterSign
		{
			get
			{
				return this._FIsCounterSign;
			}
			set
			{
				if ((this._FIsCounterSign != value))
				{
					this.OnFIsCounterSignChanging(value);
					this.SendPropertyChanging();
					this._FIsCounterSign = value;
					this.SendPropertyChanged("FIsCounterSign");
					this.OnFIsCounterSignChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAuditNodeName", DbType="VarChar(100)")]
		public string FAuditNodeName
		{
			get
			{
				return this._FAuditNodeName;
			}
			set
			{
				if ((this._FAuditNodeName != value))
				{
					this.OnFAuditNodeNameChanging(value);
					this.SendPropertyChanging();
					this._FAuditNodeName = value;
					this.SendPropertyChanged("FAuditNodeName");
					this.OnFAuditNodeNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FProcessName", DbType="VarChar(50)")]
		public string FProcessName
		{
			get
			{
				return this._FProcessName;
			}
			set
			{
				if ((this._FProcessName != value))
				{
					this.OnFProcessNameChanging(value);
					this.SendPropertyChanging();
					this._FProcessName = value;
					this.SendPropertyChanged("FProcessName");
					this.OnFProcessNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ei_departmentAuditNode_ei_departmentAuditUser", Storage="_ei_departmentAuditUser", ThisKey="id", OtherKey="FDepartmentNodeId")]
		public EntitySet<ei_departmentAuditUser> ei_departmentAuditUser
		{
			get
			{
				return this._ei_departmentAuditUser;
			}
			set
			{
				this._ei_departmentAuditUser.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ei_department_ei_departmentAuditNode", Storage="_ei_department", ThisKey="FDepartmentId", OtherKey="id", IsForeignKey=true)]
		public ei_department ei_department
		{
			get
			{
				return this._ei_department.Entity;
			}
			set
			{
				ei_department previousValue = this._ei_department.Entity;
				if (((previousValue != value) 
							|| (this._ei_department.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ei_department.Entity = null;
						previousValue.ei_departmentAuditNode.Remove(this);
					}
					this._ei_department.Entity = value;
					if ((value != null))
					{
						value.ei_departmentAuditNode.Add(this);
						this._FDepartmentId = value.id;
					}
					else
					{
						this._FDepartmentId = default(Nullable<int>);
					}
					this.SendPropertyChanged("ei_department");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ei_departmentAuditUser(ei_departmentAuditUser entity)
		{
			this.SendPropertyChanging();
			entity.ei_departmentAuditNode = this;
		}
		
		private void detach_ei_departmentAuditUser(ei_departmentAuditUser entity)
		{
			this.SendPropertyChanging();
			entity.ei_departmentAuditNode = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ei_departmentAuditUser")]
	public partial class ei_departmentAuditUser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _FDepartmentNodeId;
		
		private string _FAuditorNumber;
		
		private System.Nullable<System.DateTime> _FBeginTime;
		
		private System.Nullable<System.DateTime> _FEndTime;
		
		private System.Nullable<bool> _isDeleted;
		
		private EntityRef<ei_departmentAuditNode> _ei_departmentAuditNode;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnFDepartmentNodeIdChanging(System.Nullable<int> value);
    partial void OnFDepartmentNodeIdChanged();
    partial void OnFAuditorNumberChanging(string value);
    partial void OnFAuditorNumberChanged();
    partial void OnFBeginTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnFBeginTimeChanged();
    partial void OnFEndTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnFEndTimeChanged();
    partial void OnisDeletedChanging(System.Nullable<bool> value);
    partial void OnisDeletedChanged();
    #endregion
		
		public ei_departmentAuditUser()
		{
			this._ei_departmentAuditNode = default(EntityRef<ei_departmentAuditNode>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FDepartmentNodeId", DbType="Int")]
		public System.Nullable<int> FDepartmentNodeId
		{
			get
			{
				return this._FDepartmentNodeId;
			}
			set
			{
				if ((this._FDepartmentNodeId != value))
				{
					if (this._ei_departmentAuditNode.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFDepartmentNodeIdChanging(value);
					this.SendPropertyChanging();
					this._FDepartmentNodeId = value;
					this.SendPropertyChanged("FDepartmentNodeId");
					this.OnFDepartmentNodeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAuditorNumber", DbType="VarChar(50)")]
		public string FAuditorNumber
		{
			get
			{
				return this._FAuditorNumber;
			}
			set
			{
				if ((this._FAuditorNumber != value))
				{
					this.OnFAuditorNumberChanging(value);
					this.SendPropertyChanging();
					this._FAuditorNumber = value;
					this.SendPropertyChanged("FAuditorNumber");
					this.OnFAuditorNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FBeginTime", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> FBeginTime
		{
			get
			{
				return this._FBeginTime;
			}
			set
			{
				if ((this._FBeginTime != value))
				{
					this.OnFBeginTimeChanging(value);
					this.SendPropertyChanging();
					this._FBeginTime = value;
					this.SendPropertyChanged("FBeginTime");
					this.OnFBeginTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FEndTime", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> FEndTime
		{
			get
			{
				return this._FEndTime;
			}
			set
			{
				if ((this._FEndTime != value))
				{
					this.OnFEndTimeChanging(value);
					this.SendPropertyChanging();
					this._FEndTime = value;
					this.SendPropertyChanged("FEndTime");
					this.OnFEndTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isDeleted", DbType="Bit")]
		public System.Nullable<bool> isDeleted
		{
			get
			{
				return this._isDeleted;
			}
			set
			{
				if ((this._isDeleted != value))
				{
					this.OnisDeletedChanging(value);
					this.SendPropertyChanging();
					this._isDeleted = value;
					this.SendPropertyChanged("isDeleted");
					this.OnisDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ei_departmentAuditNode_ei_departmentAuditUser", Storage="_ei_departmentAuditNode", ThisKey="FDepartmentNodeId", OtherKey="id", IsForeignKey=true)]
		public ei_departmentAuditNode ei_departmentAuditNode
		{
			get
			{
				return this._ei_departmentAuditNode.Entity;
			}
			set
			{
				ei_departmentAuditNode previousValue = this._ei_departmentAuditNode.Entity;
				if (((previousValue != value) 
							|| (this._ei_departmentAuditNode.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ei_departmentAuditNode.Entity = null;
						previousValue.ei_departmentAuditUser.Remove(this);
					}
					this._ei_departmentAuditNode.Entity = value;
					if ((value != null))
					{
						value.ei_departmentAuditUser.Add(this);
						this._FDepartmentNodeId = value.id;
					}
					else
					{
						this._FDepartmentNodeId = default(Nullable<int>);
					}
					this.SendPropertyChanged("ei_departmentAuditNode");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_leaving_days")]
	public partial class vw_leaving_days
	{
		
		private string _applier_num;
		
		private string _applier_name;
		
		private string _leave_type;
		
		private System.Nullable<System.DateTime> _from_date;
		
		private System.Nullable<System.DateTime> _to_date;
		
		private System.Nullable<int> _work_days;
		
		private System.Nullable<decimal> _work_hours;
		
		public vw_leaving_days()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_applier_num", DbType="VarChar(50)")]
		public string applier_num
		{
			get
			{
				return this._applier_num;
			}
			set
			{
				if ((this._applier_num != value))
				{
					this._applier_num = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_applier_name", DbType="VarChar(50)")]
		public string applier_name
		{
			get
			{
				return this._applier_name;
			}
			set
			{
				if ((this._applier_name != value))
				{
					this._applier_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_leave_type", DbType="VarChar(50)")]
		public string leave_type
		{
			get
			{
				return this._leave_type;
			}
			set
			{
				if ((this._leave_type != value))
				{
					this._leave_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_from_date", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> from_date
		{
			get
			{
				return this._from_date;
			}
			set
			{
				if ((this._from_date != value))
				{
					this._from_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_to_date", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> to_date
		{
			get
			{
				return this._to_date;
			}
			set
			{
				if ((this._to_date != value))
				{
					this._to_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_work_days", DbType="Int")]
		public System.Nullable<int> work_days
		{
			get
			{
				return this._work_days;
			}
			set
			{
				if ((this._work_days != value))
				{
					this._work_days = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_work_hours", DbType="Decimal(4,1)")]
		public System.Nullable<decimal> work_hours
		{
			get
			{
				return this._work_hours;
			}
			set
			{
				if ((this._work_hours != value))
				{
					this._work_hours = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ei_workAgent")]
	public partial class ei_workAgent : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _emp_number;
		
		private string _agent_number;
		
		private System.Nullable<System.DateTime> _begin_time;
		
		private System.Nullable<System.DateTime> _end_time;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onemp_numberChanging(string value);
    partial void Onemp_numberChanged();
    partial void Onagent_numberChanging(string value);
    partial void Onagent_numberChanged();
    partial void Onbegin_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onbegin_timeChanged();
    partial void Onend_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onend_timeChanged();
    #endregion
		
		public ei_workAgent()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_number", DbType="VarChar(20)")]
		public string emp_number
		{
			get
			{
				return this._emp_number;
			}
			set
			{
				if ((this._emp_number != value))
				{
					this.Onemp_numberChanging(value);
					this.SendPropertyChanging();
					this._emp_number = value;
					this.SendPropertyChanged("emp_number");
					this.Onemp_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_agent_number", DbType="VarChar(20)")]
		public string agent_number
		{
			get
			{
				return this._agent_number;
			}
			set
			{
				if ((this._agent_number != value))
				{
					this.Onagent_numberChanging(value);
					this.SendPropertyChanging();
					this._agent_number = value;
					this.SendPropertyChanged("agent_number");
					this.Onagent_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_begin_time", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> begin_time
		{
			get
			{
				return this._begin_time;
			}
			set
			{
				if ((this._begin_time != value))
				{
					this.Onbegin_timeChanging(value);
					this.SendPropertyChanging();
					this._begin_time = value;
					this.SendPropertyChanged("begin_time");
					this.Onbegin_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_end_time", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> end_time
		{
			get
			{
				return this._end_time;
			}
			set
			{
				if ((this._end_time != value))
				{
					this.Onend_timeChanging(value);
					this.SendPropertyChanging();
					this._end_time = value;
					this.SendPropertyChanged("end_time");
					this.Onend_timeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
